// data.js - Cấu trúc mới

// data.js - Cấu trúc mới (Đã sửa lỗi cú pháp)

const allSeatData = {
  // Dữ liệu cho phiên khai mạc
  khaiMac: [
    // --- HÀNG A ---
    { id: "T1M-A-1", name: "Đại biểu Bộ Chính trị", status: "bochinhtri" },
    {
      id: "T1M-A-3",
      name: "Phó Bí thư Thường trực Tỉnh ủy",
      status: "thuongtruc",
    },
    { id: "T1M-A-5", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1M-A-7", name: "Phó Bí thư Tỉnh ủy", status: "thuongtruc" },
    { id: "T1M-A-9", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1M-A-11", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-13", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-15", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-17", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-19", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-21", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-23", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-25", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-27", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1L-A-29", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1L-A-31", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1L-A-33", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1L-A-35", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1L-A-37", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1M-A-2", name: "Bí thư Tỉnh ủy", status: "thuongtruc" },
    { id: "T1M-A-4", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1M-A-6", name: "Chủ tịch UBND tỉnh", status: "thuongtruc" },
    { id: "T1M-A-8", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1M-A-10", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1M-A-12", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-14", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-16", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-18", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-20", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-22", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-24", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-26", name: "Đại biểu TW, tỉnh bạn", status: "daibieumoi" },
    { id: "T1R-A-28", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1R-A-30", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1R-A-32", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1R-A-34", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1R-A-36", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1R-A-38", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1M-B-1", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1M-B-3", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1M-B-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-15", name: "Mẹ VNAH", status: "meVN" },
    { id: "T1L-B-17", name: "Mẹ VNAH", status: "meVN" },
    { id: "T1L-B-19", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-21", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-23", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-25", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-27", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-29", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-31", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-33", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-35", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-37", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-B-39", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-2", name: "Nguyên Thường trực", status: "nguyenthuongtruc" },
    { id: "T1M-B-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-B-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-16", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-18", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-20", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-22", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-24", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-26", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-28", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-30", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-32", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-34", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-36", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-B-38", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-1", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-3", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-15", name: "Anh hùng", status: "meVN" },
    { id: "T1L-C-17", name: "Anh hùng", status: "meVN" },
    { id: "T1L-C-19", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-21", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-23", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-25", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-27", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-29", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-31", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-33", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-35", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-37", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-39", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-C-41", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-2", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-C-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-16", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-18", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-20", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-22", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-24", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-26", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-28", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-30", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-32", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-34", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-36", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-38", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-40", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-C-42", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-1", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-3", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-15", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-D-17", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-19", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-21", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-23", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-25", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-27", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-29", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-31", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-33", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-D-35", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-2", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-D-16", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-D-18", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-20", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-22", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-24", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-26", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-28", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-30", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-32", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-34", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-D-36", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-1", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-3", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-15", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-17", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-E-19", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-21", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-23", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-25", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-27", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-29", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-31", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-33", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-35", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1L-E-37", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-2", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-E-16", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-E-18", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-20", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-22", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-24", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-26", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-28", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-30", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-32", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-34", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-36", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1R-E-38", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-1", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-3", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-15", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-17", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-F-19", name: "Công an", status: "congan" },
    { id: "T1L-F-21", name: "Công an", status: "congan" },
    { id: "T1L-F-23", name: "Xã, phường 1", status: "xaphuong1" },
    { id: "T1L-F-25", name: "Xã phường 1", status: "xaphuong1" },
    { id: "T1L-F-27", name: "Xã, phường 2", status: "xaphuong2" },
    { id: "T1L-F-29", name: "Xã phường 2", status: "xaphuong2" },
    { id: "T1L-F-39", name: "Thư ký", status: "thuky" },
    { id: "T1L-F-41", name: "Thư ký", status: "thuky" },
    { id: "T1M-F-2", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-16", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-F-18", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-F-20", name: "Quân đội", status: "quandoi" },
    { id: "T1R-F-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-F-24", name: "Xã, phường 3", status: "xaphuong3" },
    { id: "T1R-F-26", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1R-F-28", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1R-F-30", name: "Xã, phường 4", status: "xaphuong4" },
    { id: "T1R-F-32", name: "Xã phường 4", status: "xaphuong4" },
    { id: "T1R-F-34", name: "Xã phường 4", status: "xaphuong4" },
    { id: "T1M-G-1", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-3", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-5", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-7", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-9", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-11", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-13", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-15", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-17", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-G-19", name: "Công an", status: "congan" },
    { id: "T1L-G-21", name: "Công an", status: "congan" },
    { id: "T1L-G-23", name: "Xã, phường 1", status: "xaphuong1" },
    { id: "T1L-G-25", name: "Xã phường 1", status: "xaphuong1" },
    { id: "T1L-G-27", name: "Xã, phường 2", status: "xaphuong2" },
    { id: "T1L-G-29", name: "Xã phường 2", status: "xaphuong2" },
    { id: "T1M-G-2", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-4", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-6", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-8", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-10", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-12", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-14", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-16", name: "Đại biểu mời", status: "daibieumoi" },
    { id: "T1M-G-18", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-G-20", name: "Quân đội", status: "quandoi" },
    { id: "T1R-G-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-G-24", name: "Xã, phường 3", status: "xaphuong3" },
    { id: "T1R-G-26", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1R-G-28", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1R-G-30", name: "Xã, phường 4", status: "xaphuong4" },
    { id: "T1R-G-32", name: "Xã phường 4", status: "xaphuong4" },
    { id: "T1R-G-34", name: "Xã phường 4", status: "xaphuong4" },
    { id: "T1M-H-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-H-19", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-H-21", name: "Công an", status: "congan" },
    { id: "T1L-H-23", name: "Công an", status: "congan" },
    { id: "T1L-H-25", name: "Xã, phường 1", status: "xaphuong1" },
    { id: "T1L-H-27", name: "Xã phường 1", status: "xaphuong1" },
    { id: "T1L-H-29", name: "Xã, phường 2", status: "xaphuong2" },
    { id: "T1L-H-31", name: "Xã phường 2", status: "xaphuong2" },
    { id: "T1M-H-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-H-18", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-H-20", name: "Quân đội", status: "quandoi" },
    { id: "T1R-H-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-H-24", name: "Xã, phường 3", status: "xaphuong3" },
    { id: "T1R-H-26", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1R-H-28", name: "Xã phường 3", status: "xaphuong3" },
    { id: "T1M-I-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-I-19", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-I-21", name: "Công an", status: "congan" },
    { id: "T1L-I-23", name: "Công an", status: "congan" },
    { id: "T1L-I-25", name: "Xã, phường 1", status: "xaphuong1" },
    { id: "T1L-I-27", name: "Xã phường 1", status: "xaphuong1" },
    { id: "T1M-I-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-I-20", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-I-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-I-24", name: "Quân đội", status: "quandoi" },
    { id: "T1M-J-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-19", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-J-21", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-J-23", name: "Công an", status: "congan" },
    { id: "T1L-J-25", name: "Công an", status: "congan" },
    { id: "T1M-J-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-J-20", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-J-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-J-24", name: "Quân đội", status: "quandoi" },
    { id: "T1M-K-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-19", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-K-21", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1L-K-23", name: "Công an", status: "congan" },
    { id: "T1L-K-25", name: "Công an", status: "congan" },
    { id: "T1M-K-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-K-20", name: "Ủy viên BTV", status: "banthuongvu" },
    { id: "T1R-K-22", name: "Quân đội", status: "quandoi" },
    { id: "T1R-K-24", name: "Quân đội", status: "quandoi" },
    { id: "T1M-L-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-19", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-21", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-23", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-L-25", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1L-L-27", name: "Công an", status: "congan" },
    { id: "T1L-L-29", name: "Công an", status: "congan" },
    { id: "T1M-L-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-20", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-22", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-24", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-L-26", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-1", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-19", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-21", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-23", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-25", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-27", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-M-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-20", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-22", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-24", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-M-26", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
  ],

  // Dữ liệu cho phiên bế mạc
  beMac: [
    { id: "T1M-A-1", name: "Đại biểu Trung ương", status: "daibieumoi" },
    { id: "T1M-A-3", name: "Đại biểu Trung ương", status: "daibieumoi" },
    { id: "T1M-A-5", name: "Đại biểu Trung ương", status: "daibieumoi" },
    { id: "T1M-A-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-A-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-A-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
     { id: "T1L-A-13", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-A-15",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-A-2", name: "Đại biểu Trung ương", status: "daibieumoi" },
        { id: "T1M-A-4", name: "Đại biểu Trung ương", status: "daibieumoi" },
    { id: "T1M-A-6", name: "Đại biểu Trung ương", status: "daibieumoi" },
    { id: "T1M-A-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-A-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-A-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1R-A-14", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-A-16", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    //Hàng B
    { id: "T1M-B-1", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-B-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1L-B-15", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-B-17",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-B-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-B-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-B-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-B-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-B-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-B-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1R-B-14", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-B-16", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    //Hàng C
    { id: "T1M-C-1", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-C-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
       { id: "T1L-C-15", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-C-17",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-C-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-C-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1R-C-16", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-C-18", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    //Hàng D
    { id: "T1M-D-1", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-D-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1L-D-17", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-D-19",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-D-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-D-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
      { id: "T1R-D-18", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-D-20", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    //Hàng E
    { id: "T1M-E-1", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-E-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
     { id: "T1L-E-19", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-E-21",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-E-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-E-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
      { id: "T1R-E-18", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-E-20", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
       //Hàng F
    { id: "T1M-F-1", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-3", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-5", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-7", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-9", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-11", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-13", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-15", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
    { id: "T1M-F-17", name: "Đảng bộ cơ quan Đảng", status: "coquandang" },
     { id: "T1L-F-19", name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1L-F-21",  name: "Đảng bộ Công an tỉnh", status: "congan" },
    { id: "T1M-F-2", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-4", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-6", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-8", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-10", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-12", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-14", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
    { id: "T1M-F-16", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
        { id: "T1M-F-18", name: "Đảng bộ UBND tỉnh", status: "ubndtinh" },
      { id: "T1R-F-18", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
    { id: "T1R-F-20", name: "Đảng bộ Bộ CHQS tỉnh", status: "quandoi" },
  ],
};
